name: "Terraform Plan CI"
run: terraform init -upgrade



on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]



jobs:

  terraform-plan:

    name: "Terraform Plan"

    runs-on: ubuntu-latest

    

    # Set environment variables for AWS credentials

    env:

      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      AWS_REGION: "us-east-1"



    steps:

      - name: Checkout Code

        uses: actions/checkout@v4



      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3



      - name: Terraform Init

        run: terraform init



      - name: Terraform Plan

        id: plan

        run: terraform plan -out=tfplan # Saves the plan to a file



      - name: Upload Plan Artifact

        uses: actions/upload-artifact@v4

        with:

          name: terraform-plan-output

          path: tfplan
